plugins {
	id 'com.axelor.app'
}

apply from: "../libs.gradle"
apply from: "../version.gradle"

apply {
	version = openSuiteVersion
}

axelor {
	title "Odex Project"
	description "Odex Project Module"
}

dependencies {
	api project(":modules:odex-base")
  
  implementation libs.jsoup
  implementation libs.swagger_jaxrs
}
