plugins {
	id 'com.axelor.app'
	id "com.github.node-gradle.node"
}
apply from: "../libs.gradle"
apply from: "../version.gradle"

apply {
	version = openSuiteVersion
}

axelor {
	title "Odex Sale"
	description "Odex Sale Module"
}

dependencies {
	api project(":modules:odex-crm")
	implementation libs.swagger_jaxrs
	testImplementation libs.mockito
}
