plugins {
	id 'com.axelor.app'
}

apply from: "../libs.gradle"
apply from: "../version.gradle"

apply {
	version = openSuiteVersion
}

axelor {
	title "Odex CRM"
	description "Odex CRM Module"
}

dependencies {
	api project(":modules:odex-base")

	implementation libs.commons_math3
	implementation libs.swagger_jaxrs
}
