plugins {
  id 'com.axelor.app'
}

apply from: "../libs.gradle"
apply from: "../version.gradle"

apply {
  version = openSuiteVersion
}

axelor {
  title "Odex Budget"
  description "Odex Budget Module"
}

dependencies {
  api project(":modules:odex-contract")
  api project(":modules:odex-human-resource")

  implementation libs.jdom
  implementation libs.xalan
  implementation libs.xmlbeans

  implementation libs.bcprov_jdk18on
  implementation libs.bcpkix_jdk18on

  implementation libs.ical4j
  implementation libs.iban4j

  testImplementation libs.mockito
}
