plugins {
    id 'com.axelor.app'
}

apply from: "../libs.gradle"
apply from: "../version.gradle"

apply {
    version = openSuiteVersion
}

axelor {
    title "Odex Intervention"
    description "Odex Intervention Module"
}

dependencies {
    api project(":modules:odex-contract")
    api project(":modules:odex-human-resource")

    implementation libs.swagger_jaxrs
}